// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnia6ZARHPSsbl4RHHEfSflF2rbgCOU28',
    appId: '1:873944747566:web:42ea7968401f5d1d6859bf',
    messagingSenderId: '873944747566',
    projectId: 'inclass12-database',
    authDomain: 'inclass12-database.firebaseapp.com',
    storageBucket: 'inclass12-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphlnfoQVK3EKW3ZboMFs3bfnSXPVtHKo',
    appId: '1:873944747566:android:9875aa2ef7e1df126859bf',
    messagingSenderId: '873944747566',
    projectId: 'inclass12-database',
    storageBucket: 'inclass12-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1luFzaFmWNSLW6vw0ldlq4RYr58zP5o',
    appId: '1:873944747566:ios:47a8554fdea3a5c26859bf',
    messagingSenderId: '873944747566',
    projectId: 'inclass12-database',
    storageBucket: 'inclass12-database.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1luFzaFmWNSLW6vw0ldlq4RYr58zP5o',
    appId: '1:873944747566:ios:47a8554fdea3a5c26859bf',
    messagingSenderId: '873944747566',
    projectId: 'inclass12-database',
    storageBucket: 'inclass12-database.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnia6ZARHPSsbl4RHHEfSflF2rbgCOU28',
    appId: '1:873944747566:web:5cc179d9406295c86859bf',
    messagingSenderId: '873944747566',
    projectId: 'inclass12-database',
    authDomain: 'inclass12-database.firebaseapp.com',
    storageBucket: 'inclass12-database.firebasestorage.app',
  );
}
